### ISSUE TITLE
Web of Science版本更新，检测不到DOI，经过如下更改可以检测Web of Science

### ISSUE THREAD

**Issue by groele** [ChaseChoi/doi2scihub#10]
// Web of Science
    convertPlainTextDOI('.FullRTa-DOI:contains("DOI:")');

**Comment by ChaseChoi** [comment]
Feel free to create a pull request😁

**Comment by ChaseChoi** [comment]
Hi @groele, this bug has been fixed in [v1.0.22](https://greasyfork.org/en/scripts/412498-doi-to-sci-hub)
