### ISSUE TITLE
似乎对researchgate的支持有一些问题

### ISSUE THREAD

**Issue by zephyrxx** [ChaseChoi/doi2scihub#14]
比如这一篇 https://www.researchgate.net/publication/235345024_Capturing_translation_processes_to_access_metalinguistic_awareness
点击doi无法跳转到下载，希望能看一下，谢谢

**Comment by ChaseChoi** [comment]
Hi @zephyrxx , 请更新至[v1.0.28](https://greasyfork.org/en/scripts/412498-doi-to-sci-hub)。支持以下两种场景：
1. 文章详情页
2. 搜索结果页

**Comment by zephyrxx** [comment]
你好，我用的是最新的，但是点击跳转会失败

**Comment by ChaseChoi** [comment]
> 比如这一篇 https://www.researchgate.net/publication/235345024_Capturing_translation_processes_to_access_metalinguistic_awareness
> 点击doi无法跳转到下载，希望能看一下，谢谢

@zephyrxx 我使用v1.0.28可以成功跳转。你可以尝试删除脚本，重新安装以确保运行的是v1.0.28的代码。

**Comment by zephyrxx** [comment]
重新安装后解决了，感谢您的回复，非常好用，谢谢您的工作
