### ISSUE TITLE
添加匹配AMERICAN ECONOMIC ASSOCIATION，网页内DOI未识别

### ISSUE THREAD

**Issue by Taboo725** [ChaseChoi/doi2scihub#16]
本脚本未适配AEA网站，尝试自己在设置中添加网址适配后，网站中DOI号未识别高亮，反而下方的Replication Package被识别了，求解
![image](https://user-images.githubusercontent.com/76696223/236831595-b37301d7-b1a3-49c5-90f1-463225592fa7.png)

**Comment by ChaseChoi** [comment]
@Taboo725  纯文本DOI需要在代码中添加处理逻辑，会在后续版本适配，请关注更新。

**Comment by ChaseChoi** [comment]
@Taboo725 Hi, 已适配AEA，请更新至[v1.0.31](https://greasyfork.org/en/scripts/412498-doi-to-sci-hub)。相关改动可以参考[8be381d](https://github.com/ChaseChoi/doi2scihub/commit/8be381d0f3531788f06ff1e8a27421e37edf47ed)
