### ISSUE TITLE
pure text DOI to url

### ISSUE THREAD

**Issue by alphaskyler** [ChaseChoi/doi2scihub#4]
There are always some kinds of DOI text on webpages like

DOI: 10.7176/JEP/11-6-08

are we able to convert this text to an sci-hub url directly?

**Comment by ChaseChoi** [comment]
Yes. It would be nice to add this feature.

**Comment by ghost** [comment]
http://www.socolar.com/Article/Index?aid=100055099031&jid=100000001481

这个网页它不能够直接高亮，添加至用户匹配后也是不成功，请问是什么原因呢？

**Comment by ChaseChoi** [comment]
@ZZY117 Check out [v1.0.17](https://greasyfork.org/en/scripts/412498-doi-to-sci-hub)
